Name:           ros-indigo-tf-keyboard-cal
Version:        0.1.1
Release:        0%{?dist}
Summary:        ROS tf_keyboard_cal package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/davetcoleman/tf_keyboard_cal
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-keyboard
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-rosparam-shortcuts
Requires:       ros-indigo-tf
Requires:       ros-indigo-tf2
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cmake-modules
BuildRequires:  ros-indigo-keyboard
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-roslib
BuildRequires:  ros-indigo-rosparam-shortcuts
BuildRequires:  ros-indigo-tf
BuildRequires:  ros-indigo-tf2

%description
Allows manual control of a TF through the keyboard

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Jun 30 2016 Dave Coleman <davetcoleman@gmail.com> - 0.1.1-0
- Autogenerated by Bloom

* Tue Feb 09 2016 Dave Coleman <davetcoleman@gmail.com> - 0.0.6-1
- Autogenerated by Bloom

* Wed Jan 13 2016 Dave Coleman <davetcoleman@gmail.com> - 0.0.6-0
- Autogenerated by Bloom

* Sun Dec 27 2015 Dave Coleman <davetcoleman@gmail.com> - 0.0.5-0
- Autogenerated by Bloom

* Mon Dec 07 2015 Dave Coleman <davetcoleman@gmail.com> - 0.0.4-0
- Autogenerated by Bloom

* Thu Dec 03 2015 Dave Coleman <davetcoleman@gmail.com> - 0.0.3-0
- Autogenerated by Bloom

